---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: aurora-dx-aws
# description will be included in the image's metadata
description: Customized aurora-dx based OS image that includes the AWS Client VPN.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # copy in the readlink wrapper and systemd drop-in
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  # make the copy of readlink needed by the wrapper
  - type: script
    snippets:
      - "cp /usr/bin/readlink /usr/bin/readlink.orig"
  
  # install the awsclientvpn package
  - type: dnf
    repos:
      copr:
        - vorona/aws-rpm-packages
    optfix:
      - awsvpnclient
    install:
      packages:
        - awsvpnclient
  
  # automatically start the service on boot
  - type: systemd
    system:
      enabled:
        - awsvpnclient

  # this sets up the proper policy & signing files for signed images to work fully
  - type: signing

